
[crop_harvesting]
	#If the held tool should be considered when right-click harvesting
	consider_tool = true
	#The blocks that should get harvested by right-clicking
	whitelist = ["minecraft:nether_wart", "minecraft:potatoes", "minecraft:carrots", "minecraft:wheat", "minecraft:beetroots", "minecraft:cocoa", "foragecraft:leek_crop", "farmersdelight:rice_upper_crop", "farmersdelight:cabbages", "farmersdelight:onions", "farmersdelight:red_mushroom_colony", "farmersdelight:brown_mushroom_colony"]

[tree_harvesting]
	#Examples: 'minecraft:oak_log', '#minecraft:logs'
	log_types = ["minecraft:acacia_log", "minecraft:birch_log", "minecraft:dark_oak_log", "minecraft:jungle_log", "minecraft:oak_log", "minecraft:spruce_log", "minecraft:crimson_stem", "minecraft:warped_stem", "rankine:black_birch_log", "rankine:yellow_birch_log", "rankine:maple_log", "rankine:cedar_log", "rankine:pinyon_pine_log", "rankine:juniper_log", "rankine:coconut_palm_log", "rankine:balsam_fir_log", "rankine:magnolia_log", "rankine:eastern_hemlock_log", "rankine:sharinga_log", "rankine:black_walnut_log", "rankine:cork_oak_log", "rankine:cinnamon_log"]
	#Examples: 'minecraft:dirt', '#forge:sand/colorless'
	ground_types = ["minecraft:dirt", "minecraft:grass_block", "minecraft:coarse_dirt", "minecraft:podzol", "minecraft:mycelium", "minecraft:warped_nylium", "minecraft:crimson_nylium", "minecraft:netherrack"]
	#The tools which the player is allowed to harvest trees
	allowed_tree_tools = ["minecraft:wooden_axe", "minecraft:golden_axe", "minecraft:stone_axe", "minecraft:iron_axe", "minecraft:diamond_axe", "minecraft:netherite_axe", "rankine:flint_axe", "rankine:pewter_axe", "rankine:bronze_axe", "rankine:invar_axe", "rankine:steel_axe", "rankine:titanium_alloy_axe", "rankine:stainless_steel_axe", "rankine:nickel_superalloy_axe", "rankine:cobalt_superalloy_axe", "rankine:tungsten_heavy_alloy_axe", "rankine:rose_gold_axe", "rankine:white_gold_axe", "rankine:green_gold_axe", "rankine:blue_gold_axe", "rankine:purple_gold_axe", "rankine:black_gold_axe", "rankine:amalgam_axe", "rankine:alloy_axe"]
	#If the tree harvester should be enabled
	enabled = true

	[tree_harvesting.dynamic_breaking_speed]
		#The amount of breaking time that gets added per harvested log
		#Range: 0.0 ~ 100.0
		per_log = 0.1
		#The maximum amount of time a tree should take to harvest
		#Range: 1.0 ~ 100.0
		min_speed = 10.0
		#If bigger trees should be harder to break
		enabled = true

